Observational Data Investigation 
---

By Paul Duckworth 1 Sept 2017.


Initial attempt to match variables and data between Matt's observational data and ONET data. 

Starting with the snippet of "Administrator" observational data.

Observational Data:
---

In [79]:
import os
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

datasets = '/home/paul/Datasets/ONET/'
excel_doc = pd.ExcelFile(os.path.join(datasets, 'FoHC/Future of healthcare sample data.xlsx'))
data = excel_doc.parse("Data").fillna("-")
legend = excel_doc.parse("Legend")

data.head()
# legend.head()

,Occupation title,Task,GP Code,Notes,Task also done by,Task also done by.1,Dependance on other people,Technology Use,Technology use,Information work,Information work.1,Information work.2,partial automation
0,Administrator,Medical Coding,"BFS, BSC, WMC",-,deputy practice managers,secretaries,-,Desktop,specific software,reduction,-,-,no
1,Administrator,Answering Phones,"BFS, BSC",-,receptionists,-,-,Phone,-,social transaction,-,-,no
2,Administrator,Register new Patients,"BFS, BSC",-,receptionists,-,-,Desktop,paper,transfer,entry,structured,no
3,Administrator,Use Intellisense to OCR letters and pick out c...,BFS,-,-,-,Requires scanning from other staff members or ...,Desktop,software,reduction,-,-,yes
4,Administrator,Child immunization targets in open exeter,WMC,-,-,-,-,Desktop,website,transfer,-,-,yes

ONET occupation DATA:
---

In [81]:
occupations = pd.read_table(os.path.join(datasets, 'databases/db2016/Occupation Data.txt'), sep='\t')
occupations.rename(columns = {'Title':'Occupation title'}, inplace = True)
occupations.head()

,O*NET-SOC Code,Occupation title,Description
0,11-1011.00,Chief Executives,Determine and formulate policies and provide o...
1,11-1011.03,Chief Sustainability Officers,"Communicate and coordinate with management, sh..."
2,11-1021.00,General and Operations Managers,"Plan, direct, or coordinate the operations of ..."
3,11-1031.00,Legislators,"Develop, introduce or enact laws and statutes ..."
4,11-2011.00,Advertising and Promotions Managers,"Plan, direct, or coordinate advertising polici..."

In [109]:
admin = occupations[occupations['Occupation title'].str.contains("General Practitioner", na=False)]
admin

,O*NET-SOC Code,Occupation title,Description
463,29-1062.00,Family and General Practitioners,"Physicians who diagnose, treat, and help preve..."

In [87]:
scretaries = occupations[occupations['Occupation title'].str.contains("Medical Secretaries", na=False)]
# scretaries['O*NET-SOC Code']
scretaries.head()

# technicians = occupations[occupations['O*NET-SOC Code'] == '29-2071.00']
# technicians.head()

,O*NET-SOC Code,Occupation title,Description
747,43-6013.00,Medical Secretaries,Perform secretarial duties using specific know...

In [110]:
# Alternate occupation titles per SOC:
alt_titles = pd.read_table(os.path.join(datasets, 'databases/db2016/Alternate Titles.txt'), sep='\t')
alt = alt_titles[ alt_titles["O*NET-SOC Code"] == '29-1062.00']
alt.head()

      O*NET-SOC Code                    Alternate Title Short Title Source(s)
17739     29-1062.00   Board Certified Family Physician         n/a     02,04
17740     29-1062.00                             Doctor         n/a        08
17741     29-1062.00       Emergency Medicine Physician         n/a        09
17742     29-1062.00  Emergency Room Doctor (ER Doctor)   ER Doctor        09
17743     29-1062.00          Family Medicine Physician         n/a     02,04

In [89]:
# # reported occupation titles 
sample_titles = pd.read_table(os.path.join(datasets, 'databases/db2016/Sample of Reported Titles.txt'), sep='\t')
# sample_titles[ sample_titles["O*NET-SOC Code"] == '43-6013.00']

In [4]:
# Merging Matts to ONET based on Occupation doesn't work - more detail in the ONET occupation titles.
# How to merge? - assign SOC codes?  

# merged = pd.merge(data, admin, on='Occupation title', how='outer')
# merged.head()

Other ONET Datasets: 
---

In [111]:
#Tasks per SOC:
tasks = pd.read_table(os.path.join(datasets, 'databases/db2016/Task Statements.txt'), sep='\t')
tasks[ tasks['O*NET-SOC Code'] == '29-1062.00']  # # Medical Secretaries

,O*NET-SOC Code,Task ID,Task,Task Type,Incumbents Responding,Date,Domain Source
8552,29-1062.00,7771,"Prescribe or administer treatment, therapy, me...",Core,61,07/2011,Incumbent
8553,29-1062.00,7772,"Order, perform, and interpret tests and analyz...",Core,61,07/2011,Incumbent
8554,29-1062.00,7774,"Collect, record, and maintain patient informat...",Core,61,07/2011,Incumbent
8555,29-1062.00,7773,Monitor patients' conditions and progress and ...,Core,61,07/2011,Incumbent
8556,29-1062.00,7775,Explain procedures and discuss test results or...,Core,61,07/2011,Incumbent
8557,29-1062.00,7776,Advise patients and community members concerni...,Core,61,07/2011,Incumbent
8558,29-1062.00,7777,Refer patients to medical specialists or other...,Core,61,07/2011,Incumbent
8559,29-1062.00,7779,"Coordinate work with nurses, social workers, r...",Core,61,07/2011,Incumbent
8560,29-1062.00,7778,"Direct and coordinate activities of nurses, st...",Core,60,07/2011,Incumbent
8561,29-1062.00,7782,"Plan, implement, or administer health programs...",Core,60,07/2011,Incumbent
8562,29-1062.00,7780,Deliver babies.,Supplemental,61,07/2011,Incumbent
8563,29-1062.00,7781,"Operate on patients to remove, repair, or impr...",Supplemental,60,07/2011,Incumbent
8564,29-1062.00,20120,"Train residents, medical students, and other h...",Supplemental,60,07/2011,Incumbent
8565,29-1062.00,20121,Prepare government or organizational reports w...,Supplemental,60,07/2011,Incumbent
8566,29-1062.00,7784,Conduct research to study anatomy and develop ...,Supplemental,60,07/2011,Incumbent

In [92]:
#Task DWAs (detailed work activitiy code):
taskDWA = pd.read_table(os.path.join(datasets, 'databases/db2016/Tasks to DWAs.txt'), sep='\t')
taskDWA[ taskDWA['O*NET-SOC Code'] == '43-6013.00'].head()  # # Medical Secretaries

      O*NET-SOC Code  Task ID             DWA ID     Date Domain Source
15406     43-6013.00    20438  4.A.2.b.5.I03.D01  03/2014       Analyst
15407     43-6013.00      775  4.A.2.b.5.I03.D01  03/2014       Analyst
15408     43-6013.00      776  4.A.2.a.2.I03.D03  03/2014       Analyst
15409     43-6013.00      776  4.A.3.b.6.I11.D05  03/2014       Analyst
15410     43-6013.00      777  4.A.4.a.3.I03.D11  03/2014       Analyst

In [93]:
#Task DWAs ratings:
task_rat = pd.read_table(os.path.join(datasets, 'databases/db2016/Task Ratings.txt'), sep='\t')
task_rat[ task_rat['Task ID'] == 777]    # # Answer telephones and direct calls

,O*NET-SOC Code,Task ID,Scale ID,Category,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Date,Domain Source
118044,43-6013.00,20438,FT,1,3.53,70,3.11,0.59,18.45,N,07/2013,Incumbent
118045,43-6013.00,20438,FT,2,9.44,70,3.95,3.98,20.77,N,07/2013,Incumbent
118046,43-6013.00,20438,FT,3,3.30,70,1.74,1.14,9.21,N,07/2013,Incumbent
118047,43-6013.00,20438,FT,4,16.20,70,5.60,7.83,30.55,N,07/2013,Incumbent
118048,43-6013.00,20438,FT,5,15.79,70,6.32,6.77,32.62,N,07/2013,Incumbent
118049,43-6013.00,20438,FT,6,9.57,70,3.48,4.53,19.11,N,07/2013,Incumbent
118050,43-6013.00,20438,FT,7,42.17,70,7.77,27.86,57.93,N,07/2013,Incumbent
118051,43-6013.00,20438,IM,n/a,4.45,71,0.14,4.18,4.72,N,07/2013,Incumbent
118052,43-6013.00,20438,RT,n/a,59.75,116,5.75,48.04,70.45,N,07/2013,Incumbent

In [112]:
#Categorise Detailed Work Activities, 1-5 increasing frequency. 
task_cats = pd.read_table(os.path.join(datasets, 'databases/db2016/Task Categories.txt'), sep='\t')
task_cats

  Scale ID  Category Category Description
0       FT         1       Yearly or less
1       FT         2     More than yearly
2       FT         3    More than monthly
3       FT         4     More than weekly
4       FT         5                Daily
5       FT         6  Several times daily
6       FT         7       Hourly or more

In [96]:
# tasks_green = pd.read_table(os.path.join(datasets, 'databases/db2016/Tasks to Green DWAs.txt'), sep='\t')
# tasks_green.head()

In [98]:
DWA = pd.read_table(os.path.join(datasets, 'databases/db2016/DWA Reference.txt'), sep='\t')
DWA.head()

DWA[ DWA["DWA ID"] == "4.A.4.a.3.I03.D11"]

,Element ID,IWA ID,DWA ID,DWA Title
1604,4.A.4.a.3,4.A.4.a.3.I03,4.A.4.a.3.I03.D11,Answer telephones to direct calls or provide i...

In [66]:
# Intermediate Work Activity and corresponding WA element ID. 
# Every IWA is linked to exactly one WA from the O*NET Content Model. 
# IWAs are linked to one or more DWAs; 

IWA = pd.read_table(os.path.join(datasets, 'databases/db2016/IWA Reference.txt'), sep='\t')
IWA.head()

IWA[ IWA["Element ID"] == "4.A.4.a.3"]

,Element ID,IWA ID,IWA Title
257,4.A.4.a.3,4.A.4.a.3.I01,Present information in legal proceedings.
258,4.A.4.a.3,4.A.4.a.3.I02,Provide information or assistance to the public.
259,4.A.4.a.3,4.A.4.a.3.I03,"Provide information to guests, clients, or cus..."

In [106]:
# Work Analysis: Provide a mapping of SOC codes (occupations) to Work Activity ratings.
WA = pd.read_table(os.path.join(datasets, 'databases/db2016/Work Activities.txt'), sep='\t')
WA.head()

# WA[ (WA["Element ID"] == "4.A.4.a.3") & (WA["O*NET-SOC Code"] == '43-6013.00')] 
WA[ WA["O*NET-SOC Code"] == '43-6013.00'].head()

,O*NET-SOC Code,Element ID,Element Name,Scale ID,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source
53628,43-6013.00,4.A.1.a.1,Getting Information,IM,4.40,38,0.18,4.03,4.77,N,n/a,07/2013,Incumbent
53629,43-6013.00,4.A.1.a.1,Getting Information,LV,4.04,35,0.31,3.42,4.67,N,N,07/2013,Incumbent
53630,43-6013.00,4.A.1.a.2,"Monitor Processes, Materials, or Surroundings",IM,3.15,38,0.29,2.56,3.75,N,n/a,07/2013,Incumbent
53631,43-6013.00,4.A.1.a.2,"Monitor Processes, Materials, or Surroundings",LV,3.32,37,0.41,2.49,4.15,N,N,07/2013,Incumbent
53632,43-6013.00,4.A.1.b.1,"Identifying Objects, Actions, and Events",IM,3.73,37,0.24,3.24,4.23,N,n/a,07/2013,Incumbent

In [100]:
WA = pd.read_table(os.path.join(datasets, 'databases/db2016/Work Activities.txt'), sep='\t')
WA.head()

WA[ (WA["Element ID"] == "4.A.4.a.3") & (WA["O*NET-SOC Code"] == '43-6013.00')]

,O*NET-SOC Code,Element ID,Element Name,Scale ID,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source
53680,43-6013.00,4.A.4.a.3,Communicating with Persons Outside Organization,IM,3.79,38,0.21,3.36,4.22,N,n/a,07/2013,Incumbent
53681,43-6013.00,4.A.4.a.3,Communicating with Persons Outside Organization,LV,3.63,38,0.40,2.82,4.45,N,N,07/2013,Incumbent

In [46]:
# "Medical Records and Health Information Technicians Bright Outlook" Tasks:

# tasks = pd.read_table(os.path.join(datasets, 'databases/db2016/Task Statements.txt'), sep='\t')
# tasks[ tasks['O*NET-SOC Code'] == '29-2071.00']

In [9]:
#Education: 
edu = pd.read_table(os.path.join(datasets, 'databases/db2016/Education, Training, and Experience.txt'), sep='\t')
edu = edu[edu['Data Value'] != 0.0]
# edu.head()

# edu[ edu['O*NET-SOC Code'] == '29-2071.00']

In [56]:
#Technoogy:
tech = pd.read_table(os.path.join(datasets, 'databases/db2016/Tools and Technology.txt'), sep='\t')
# tech[tech['Hot Technology'] == 'Y'].head()
# tech.head()

# tech[ tech['O*NET-SOC Code'] == '43-6013.00']  # # Medical Records and Health Information Technicians

In [113]:
#SKills:
skills = pd.read_table(os.path.join(datasets, 'databases/db2016/Skills.txt'), sep='\t')
skills.head()

skills[ skills['O*NET-SOC Code'] == '43-6013.00']

,O*NET-SOC Code,Element ID,Element Name,Scale ID,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source
45780,43-6013.00,2.A.1.a,Reading Comprehension,IM,3.25,8,0.16,2.93,3.57,N,n/a,07/2013,Analyst
45781,43-6013.00,2.A.1.a,Reading Comprehension,LV,3.12,8,0.13,2.88,3.37,N,N,07/2013,Analyst
45782,43-6013.00,2.A.1.b,Active Listening,IM,3.88,8,0.13,3.63,4.12,N,n/a,07/2013,Analyst
45783,43-6013.00,2.A.1.b,Active Listening,LV,3.75,8,0.16,3.43,4.07,N,N,07/2013,Analyst
45784,43-6013.00,2.A.1.c,Writing,IM,3.12,8,0.13,2.88,3.37,N,n/a,07/2013,Analyst
45785,43-6013.00,2.A.1.c,Writing,LV,3.12,8,0.13,2.88,3.37,N,N,07/2013,Analyst
45786,43-6013.00,2.A.1.d,Speaking,IM,4.00,8,0.19,3.63,4.37,N,n/a,07/2013,Analyst
45787,43-6013.00,2.A.1.d,Speaking,LV,3.38,8,0.18,3.02,3.73,N,N,07/2013,Analyst
45788,43-6013.00,2.A.1.e,Mathematics,IM,2.00,8,0.00,2.00,2.00,N,n/a,07/2013,Analyst
45789,43-6013.00,2.A.1.e,Mathematics,LV,2.00,8,0.00,2.00,2.00,N,N,07/2013,Analyst
45790,43-6013.00,2.A.1.f,Science,IM,1.25,8,0.16,1.00,1.57,N,n/a,07/2013,Analyst
45791,43-6013.00,2.A.1.f,Science,LV,0.25,8,0.16,0.00,0.57,N,Y,07/2013,Analyst
45792,43-6013.00,2.A.2.a,Critical Thinking,IM,3.00,8,0.00,3.00,3.00,N,n/a,07/2013,Analyst
45793,43-6013.00,2.A.2.a,Critical Thinking,LV,3.00,8,0.00,3.00,3.00,N,N,07/2013,Analyst
45794,43-6013.00,2.A.2.b,Active Learning,IM,2.12,8,0.13,1.88,2.37,N,n/a,07/2013,Analyst
45795,43-6013.00,2.A.2.b,Active Learning,LV,2.38,8,0.18,2.02,2.73,N,N,07/2013,Analyst
45796,43-6013.00,2.A.2.c,Learning Strategies,IM,2.00,8,0.00,2.00,2.00,N,n/a,07/2013,Analyst
45797,43-6013.00,2.A.2.c,Learning Strategies,LV,2.00,8,0.00,2.00,2.00,N,N,07/2013,Analyst
45798,43-6013.00,2.A.2.d,Monitoring,IM,3.00,8,0.00,3.00,3.00,N,n/a,07/2013,Analyst
45799,43-6013.00,2.A.2.d,Monitoring,LV,2.62,8,0.18,2.27,2.98,N,N,07/2013,Analyst
45800,43-6013.00,2.B.1.a,Social Perceptiveness,IM,3.12,8,0.13,2.88,3.37,N,n/a,07/2013,Analyst
45801,43-6013.00,2.B.1.a,Social Perceptiveness,LV,3.00,8,0.00,3.00,3.00,N,N,07/2013,Analyst
45802,43-6013.00,2.B.1.b,Coordination,IM,3.12,8,0.13,2.88,3.37,N,n/a,07/2013,Analyst
45803,43-6013.00,2.B.1.b,Coordination,LV,2.88,8,0.13,2.63,3.12,N,N,07/2013,Analyst
45804,43-6013.00,2.B.1.c,Persuasion,IM,2.25,8,0.16,1.93,2.57,N,n/a,07/2013,Analyst
45805,43-6013.00,2.B.1.c,Persuasion,LV,2.12,8,0.13,1.88,2.37,N,N,07/2013,Analyst
45806,43-6013.00,2.B.1.d,Negotiation,IM,2.12,8,0.13,1.88,2.37,N,n/a,07/2013,Analyst
45807,43-6013.00,2.B.1.d,Negotiation,LV,2.12,8,0.13,1.88,2.37,N,N,07/2013,Analyst
45808,43-6013.00,2.B.1.e,Instructing,IM,2.25,8,0.16,1.93,2.57,N,n/a,07/2013,Analyst
45809,43-6013.00,2.B.1.e,Instructing,LV,2.12,8,0.13,1.88,2.37,N,N,07/2013,Analyst
...,...,...,...,...,...,...,...,...,...,...,...,...,...
45820,43-6013.00,2.B.3.d,Installation,IM,1.00,8,0.00,1.00,1.00,N,n/a,07/2013,Analyst
45821,43-6013.00,2.B.3.d,Installation,LV,0.00,8,0.00,0.00,0.00,N,Y,07/2013,Analyst
45822,43-6013.00,2.B.3.e,Programming,IM,1.25,8,0.16,1.00,1.57,N,n/a,07/2013,Analyst
45823,43-6013.00,2.B.3.e,Programming,LV,0.25,8,0.16,0.00,0.57,N,Y,07/2013,Analyst
45824,43-6013.00,2.B.3.g,Operation Monitoring,IM,1.88,8,0.13,1.63,2.12,N,n/a,07/2013,Analyst
45825,43-6013.00,2.B.3.g,Operation Monitoring,LV,1.12,8,0.23,0.68,1.57,N,N,07/2013,Analyst
45826,43-6013.00,2.B.3.h,Operation and Control,IM,1.00,8,0.00,1.00,1.00,N,n/a,07/2013,Analyst
45827,43-6013.00,2.B.3.h,Operation and Control,LV,0.00,8,0.00,0.00,0.00,N,Y,07/2013,Analyst
45828,43-6013.00,2.B.3.j,Equipment Maintenance,IM,1.00,8,0.00,1.00,1.00,N,n/a,07/2013,Analyst
45829,43-6013.00,2.B.3.j,Equipment Maintenance,LV,0.00,8,0.00,0.00,0.00,N,Y,07/2013,Analyst
45830,43-6013.00,2.B.3.k,Troubleshooting,IM,1.00,8,0.00,1.00,1.00,N,n/a,07/2013,Analyst
45831,43-6013.00,2.B.3.k,Troubleshooting,LV,0.00,8,0.00,0.00,0.00,N,Y,07/2013,Analyst
45832,43-6013.00,2.B.3.l,Repairing,IM,1.00,8,0.00,1.00,1.00,N,n/a,07/2013,Analyst
45833,43-6013.00,2.B.3.l,Repairing,LV,0.00,8,0.00,0.00,0.00,N,Y,07/2013,Analyst
45834,43-6013.00,2.B.3.m,Quality Control Analysis,IM,1.12,8,0.13,1.00,1.37,N,n/a,07/2013,Analyst
45835,43-6013.00,2.B.3.m,Quality Control Analysis,LV,0.25,8,0.25,0.00,0.74,N,Y,07/2013,Analyst
45836,43-6013.00,2.B.4.e,Judgment and Decision Making,IM,2.75,8,0.16,2.43,3.07,N,n/a,07/2013,Analyst
45837,43-6013.00,2.B.4.e,Judgment and Decision Making,LV,2.38,8,0.18,2.02,2.73,N,N,07/2013,Analyst
45838,43-6013.00,2.B.4.g,Systems Analysis,IM,2.00,8,0.00,2.00,2.00,N,n/a,07/2013,Analyst
45839,43-6013.00,2.B.4.g,Systems Analysis,LV,2.12,8,0.13,1.88,2.37,N,N,07/2013,Analyst
45840,43-6013.00,2.B.4.h,Systems Evaluation,IM,2.00,8,0.00,2.00,2.00,N,n/a,07/2013,Analyst
45841,43-6013.00,2.B.4.h,Systems Evaluation,LV,1.88,8,0.13,1.63,2.12,N,N,07/2013,Analyst
45842,43-6013.00,2.B.5.a,Time Management,IM,3.12,8,0.13,2.88,3.37,N,n/a,07/2013,Analyst
45843,43-6013.00,2.B.5.a,Time Management,LV,2.88,8,0.13,2.63,3.12,N,N,07/2013,Analyst
45844,43-6013.00,2.B.5.b,Management of Financial Resources,IM,1.38,8,0.26,1.00,1.89,N,n/a,07/2013,Analyst
45845,43-6013.00,2.B.5.b,Management of Financial Resources,LV,0.38,8,0.26,0.00,0.89,N,Y,07/2013,Analyst
45846,43-6013.00,2.B.5.c,Management of Material Resources,IM,1.38,8,0.26,1.00,1.89,N,n/a,07/2013,Analyst
45847,43-6013.00,2.B.5.c,Management of Material Resources,LV,0.62,8,0.42,0.00,1.45,N,Y,07/2013,Analyst
45848,43-6013.00,2.B.5.d,Management of Personnel Resources,IM,2.75,8,0.16,2.43,3.07,N,n/a,07/2013,Analyst
45849,43-6013.00,2.B.5.d,Management of Personnel Resources,LV,2.12,8,0.23,1.68,2.57,N,N,07/2013,Analyst

In [103]:
# WA[ (WA["Element ID"] == "2.A.1.a")