ONET Occupations Dataset
---

By Paul Duckworth 20th Sept 2017.

Create an ONET dataset of Occupations vs variables.

Observational Data:
---

In [5]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

datasets = '/home/paul/Datasets/ONET/'
excel_doc = pd.ExcelFile(os.path.join(datasets, 'FoHC/Future of healthcare sample data.xlsx'))
matts_data = excel_doc.parse("Data").fillna("-")

matts_data

,Occupation title,Task,GP Code,Notes,Task also done by,Task also done by.1,Dependance on other people,Technology Use,Technology use,Information work,Information work.1,Information work.2,partial automation
0,Administrator,Medical Coding,"BFS, BSC, WMC",-,deputy practice managers,secretaries,-,Desktop,specific software,reduction,-,-,no
1,Administrator,Answering Phones,"BFS, BSC",-,receptionists,-,-,Phone,-,social transaction,-,-,no
2,Administrator,Register new Patients,"BFS, BSC",-,receptionists,-,-,Desktop,paper,transfer,entry,structured,no
3,Administrator,Use Intellisense to OCR letters and pick out c...,BFS,-,-,-,Requires scanning from other staff members or ...,Desktop,software,reduction,-,-,yes
4,Administrator,Child immunization targets in open exeter,WMC,-,-,-,-,Desktop,website,transfer,-,-,yes
5,Administrator,Letter writing,MWMC,-,receptionists,secretaries,Requires scanning from other staff members or ...,Desktop,software,transfer,bricolage,-,yes
6,Administrator,Provide data to GPs from pallative care meetings,WMC,-,-,-,-,Desktop,-,social transaction,transfer,-,no
7,Administrator,Enter data for enhanced services,WMC,-,-,-,-,Desktop,website,transfer,social transaction,-,yes
8,Administrator,Write QOF letters or texts,WMC,-,deputy practice manager,-,-,Desktop,software,transfer,-,-,yes
9,Administrator,Process prescription declaration forms,WMC,-,-,-,GPs look over/signoff prior,Desktop,-,structured,error checking,-,no
10,Administrator,Audit form,WMC,-,-,-,-,Desktop,-,structured,bricolage,unstructured,no
11,Administrator,Work in CQRS,"MWC, BFS",-,receptionists,secretaries,-,Desktop,-,transfer,structured,-,yes (reporting)
12,Administrator,Mass mail letters for checkups using DocMail,WMC,-,-,-,-,Desktop,website,transfer,structured,-,yes
13,Administrator,Scan documents,"BSC, WMC",-,receptionists,-,-,Desktop,software,structured,-,-,yes
14,Administrator,Caretaking of health record addressing changes...,BSC,-,-,-,-,Desktop,software,unstructured,bricolage,-,no
15,Administrator,Letter Scanning,"BFS, BSC",-,-,-,-,Desktop,software,structured,-,-,yes

## ONET occupation data:

Original occupation dataset only have SOC code, Title and description.

In [15]:
occupations = pd.read_table(os.path.join(datasets, 'databases/db2016/Occupation Data.txt'), sep='\t')
occupations.rename(columns = {'Title':'O*NET Occupation title'}, inplace = True)

occupations[occupations['O*NET Occupation title'].str.contains('Care', na=False)]
# occupations[occupations['Description'].str.contains('manager', na=False)]

# print occupations[occupations['O*NET-SOC Code'] == '43-6014.00']
# print occupations[occupations['O*NET-SOC Code'] == '43-6011.00']
# print occupations[occupations['O*NET-SOC Code'] == '43-9199.00']

man_soc = '11-9111.00'

In [116]:
# occupations_observed = {'Administrator' :  'Medical Records and Health Information Technician',
#     'General Practitioner':    'Family and General Practitioners',
#     'Healthcare Assistant':    ['Medical Assistants', 'Nursing Assistants'],
#     'Pharmacy technician':     'Pharmacy Technicians',
#     'Phlebotomist':            'Phlebotomists',
#     'Practice manager':        'Medical and Health Services Managers',
#     'Deputy Practice Manager': 'Medical and Health Services Managers',
#     'Practice nurse':          ['Nurse Practitioners', 'Registered Nurses'],
#     'Receptionist':            'Receptionists and Information Clerks',
#     'Scanning Clerk':          'Information and Record Clerks, All Other',
#     'Secretary':               'Medical Secretaries'}

# list_of_onet_occs = [item for sublist in occupations_mapping.keys() for item in sublist]

occupations_mapping = {'Medical Secretaries' :                      'Secretary',    
                       'Family and General Practitioners':          'General Practitioner',
                       'Medical Assistants':                        'Healthcare Assistant',
                       'Nursing Assistants':                        'Healthcare Assistant',
                       'Pharmacy Technicians' :                     'Pharmacy technician',
                       'Phlebotomist':                              'Phlebotomists',
                       'Medical and Health Services Managers' :     'Practice manager',
                       '                                 ' :        'Deputy Practice Manager',
                       'Nurse Practitioners':                       'Practice nurse', 
                       'Registered Nurses':                         'Practice nurse',
                       'Receptionists and Information Clerks' :     'Receptionist',
                       'Information and Record Clerks, All Other' : 'Scanning Clerk',
                       'Medical Records and Health Information Technician': 'Administrator'}

# Empty Frame
df = pd.DataFrame(columns=['Observed Occupation', 'O*NET-SOC Code', 'O*NET Occupation title', 'Description'])

# Add rows which contain occupations

for ind, (onet_occ, ob_occ) in enumerate(sorted(occupations_mapping.items())): 
  
    soc = occupations[occupations['O*NET Occupation title'].str.contains(onet_occ, na=False)]
    soc['Observed Occupation'] = ob_occ
    df = pd.concat([df, soc])
#     occu = pd.concat([occu,row])

# df.index = [range(len(occupations_mapping))]

cols = ['Observed Occupation', 'O*NET-SOC Code', 'O*NET Occupation title', 'Description']
df = df[cols]
# df.to_csv('/home/paul/example.csv')

df

/home/paul/Documents/Oxford/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,Observed Occupation,O*NET-SOC Code,O*NET Occupation title,Description
463,General Practitioner,29-1062.00,Family and General Practitioners,"Physicians who diagnose, treat, and help preve..."
727,Scanning Clerk,43-4199.00,"Information and Record Clerks, All Other",All information and record clerks not listed s...
555,Healthcare Assistant,31-9092.00,Medical Assistants,Perform administrative and certain clinical du...
530,Administrator,29-2071.00,Medical Records and Health Information Technic...,"Compile, process, and maintain medical records..."
747,Secretary,43-6013.00,Medical Secretaries,Perform secretarial duties using specific know...
46,Practice manager,11-9111.00,Medical and Health Services Managers,"Plan, direct, or coordinate medical and health..."
504,Practice nurse,29-1171.00,Nurse Practitioners,"Diagnose and treat acute, episodic, or chronic..."
547,Healthcare Assistant,31-1014.00,Nursing Assistants,Provide basic patient care under direction of ...
523,Pharmacy technician,29-2052.00,Pharmacy Technicians,Prepare medications under the direction of a p...
560,Phlebotomists,31-9097.00,Phlebotomists,"Draw blood for tests, transfusions, donations,..."
725,Receptionist,43-4171.00,Receptionists and Information Clerks,Answer inquiries and provide information to th...
497,Practice nurse,29-1141.00,Registered Nurses,"Assess patient health problems and needs, deve..."

In [8]:
# alt_titles[ alt_titles["O*NET-SOC Code"].str.contains('29-1062.00') ]

## Alternate Titles 

Somehow merge the other titles reported for each of the observed Occupation Titles

In [26]:
# Alternate occupation titles per SOC:
alt_titles = pd.read_table(os.path.join(datasets, 'databases/db2016/Alternate Titles.txt'), sep='\t')

# # reported occupation titles 
sample_titles = pd.read_table(os.path.join(datasets, 'databases/db2016/Sample of Reported Titles.txt'), sep='\t')

for soc in df['O*NET-SOC Code']:
    alt = alt_titles[ alt_titles["O*NET-SOC Code"].str.contains(soc) ]
    print "???", soc, alt 
    for a in alt['Alternate Title']:
        x = occupations[occupations['Occupation title'].str.contains(a, na=False)]
#         if len(x)==1: print  "alt = ",  a, " soc =  ", x['O*NET-SOC Code'], x['O*NET-SOC Code'].astype(str)

# print ""            
#print other_socs

??? 29-1062.00       O*NET-SOC Code                                    Alternate Title  \
17739     29-1062.00                   Board Certified Family Physician
17740     29-1062.00                                             Doctor
17741     29-1062.00                       Emergency Medicine Physician
17742     29-1062.00                  Emergency Room Doctor (ER Doctor)
17743     29-1062.00                          Family Medicine Physician
17744     29-1062.00                                   Family Physician
17745     29-1062.00                             Family Practice Doctor
17746     29-1062.00  Family Practice MD (Family Practice Medical Do...
17747     29-1062.00             Family Practice Medical Doctor (FP MD)
17748     29-1062.00                          Family Practice Physician
17749     29-1062.00                                Family Practitioner
17750     29-1062.00                                Geriatric Physician
17751     29-1062.00                                       Geriatrician
17752     29-1062.00                        Internal Medicine Physician
17753     29-1062.00                                   Medical Director
17754     29-1062.00                                Medical Doctor (MD)
17755     29-1062.00                            Medical Staff Physician
17756     29-1062.00                    Occupational Medicine Physician
17757     29-1062.00                             Occupational Physician
17758     29-1062.00                                       Pediatrician
17759     29-1062.00                                          Physician
17760     29-1062.00                                Physician Assistant
17761     29-1062.00                            Physicians and Surgeons
17762     29-1062.00                                     Police Surgeon
17763     29-1062.00      Primary Care MD (Primary Care Medical Doctor)
17764     29-1062.00                             Primary Care Physician
17765     29-1062.00                              Primary Care Provider
17766     29-1062.00                            Public Health Physician
17767     29-1062.00                              Treatment Coordinator

              Short Title Source(s)
17739                 n/a     02,04
17740                 n/a        08
17741                 n/a        09
17742           ER Doctor        09
17743                 n/a     02,04
17744                 n/a     02,04
17745                 n/a        02
17746  Family Practice MD        02
17747               FP MD     02,04
17748                 n/a  02,04,09
17749                 n/a     02,04
17750                 n/a        08
17751                 n/a        08
17752                 n/a        02
17753                 n/a        02
17754                  MD     02,08
17755                 n/a        02
17756                 n/a        02
17757                 n/a        08
17758                 n/a        02
17759                 n/a        02
17760                 n/a        02
17761                 n/a        08
17762                 n/a        08
17763     Primary Care MD        02
17764                 n/a        02
17765                 n/a        02
17766                 n/a        08
17767                 n/a        09

KeyError: 'Occupation title'

In [10]:

# sample_titles[ sample_titles["O*NET-SOC Code"] == '43-6013.00']

In [11]:
# Merging Matts to ONET based on Occupation doesn't work - more detail in the ONET occupation titles.
# How to merge? - assign SOC codes?  

# merged = pd.merge(data, admin, on='Occupation title', how='outer')
# merged.head()

Merge Other ONET variables: 
---

In [136]:
#Tasks per SOC:
tasks = pd.read_table(os.path.join(datasets, 'databases/db2016/Task Statements.txt'), sep='\t')
print "\nnumber of unique all Tasks = ", tasks["Task ID"].nunique()

tasks = tasks[ tasks['O*NET-SOC Code'].isin(df['O*NET-SOC Code'].values)]

vocabulary = dict(zip(tasks['Task ID'], tasks['Task']))
print "\nvocabuary of task ids = ", vocabulary.keys()

print "\nan example: 777 ", vocabulary[777]
print "an example: 778 ", vocabulary[778]

variables = ['O*NET-SOC Code', 'Task ID']
tasks = tasks[variables]
tasks['bin'] = 1

pivot = tasks.pivot(index = 'O*NET-SOC Code', columns='Task ID', values='bin').fillna(0)
pivot

number of unique all Tasks =  19566

vocabuary of task ids =  [530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 546, 547, 548, 549, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 7771, 7772, 7773, 7774, 7775, 7776, 7777, 7778, 7779, 7780, 7781, 7782, 7784, 19389, 18544, 18545, 18546, 20120, 20121, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753, 754, 755, 756, 757, 758, 759, 760, 761, 762, 19386, 20438, 775, 776, 777, 778, 779, 780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 1839, 1840, 1841, 1842, 1843, 1844, 1845, 1846, 1847, 1848, 1849, 1850, 1851, 1852, 1854, 1855, 1856, 1857, 1858, 1859, 1860, 1861, 1862, 1863, 1864, 1865, 1866, 19342, 19347, 19316, 19317, 19318, 19319, 19320, 19321, 19322, 19323, 19324, 19325, 19326, 19327, 19328, 19329, 19330, 19331, 19332, 19333, 19334, 19335, 19336, 19337, 19338, 19339, 19340, 19341, 15246, 19343, 19344, 19345, 19346, 1939, 1940, 1941, 1943, 1944, 1945, 1946, 1947, 1949, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 19373, 19374, 19375, 19376, 19377, 19378, 19379, 19380, 19381, 19382, 19383, 19384, 19385, 19348, 19387, 19388, 20413, 19390, 19391, 19392, 19393, 19394, 19395, 19396, 18378, 18379, 18380, 18381, 18382, 18383, 18384, 18385, 18386, 18387, 18388, 18389, 18390, 18391, 18392, 18393, 18394, 18395, 18396, 18397, 18398, 18399, 18400, 18401, 18402, 18403, 18404, 2024, 2025, 2026, 2027, 2028, 2029, 2030, 2031, 2032, 2033, 2034, 2035, 2036, 2037, 2038, 2039, 2040, 2041, 2042, 2043]

an example: 777  Answer telephones and direct calls to appropriate staff.
an example: 778  Receive and route messages or documents, such as laboratory results, to appropriate staff.

Task ID,46,47,48,49,50,51,52,53,54,55,...,19391,19392,19393,19394,19395,19396,20120,20121,20413,20438
O*NET-SOC Code,,,,,,,,,,,,,,,,,,,,,
11-9111.00,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29-1062.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
29-1141.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
29-1171.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29-2052.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29-2071.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31-1014.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31-9092.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31-9097.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0
43-4171.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
43-6013.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [106]:
print "\nnumber of unique Tasks observed (for 12 occupations) = ", sum(pivot.sum(axis = 0)==1)

number of unique Tasks observed (for 12 occupations) =  240

In [72]:
#Task DWAs (detailed work activitiy code):
taskDWA = pd.read_table(os.path.join(datasets, 'databases/db2016/Tasks to DWAs.txt'), sep='\t')
taskDWA = taskDWA[ taskDWA['O*NET-SOC Code'].isin(df['O*NET-SOC Code'].values)]
taskDWA[ taskDWA['O*NET-SOC Code'] == '43-6013.00']  # # Medical Secretaries

      O*NET-SOC Code  Task ID             DWA ID     Date Domain Source
15406     43-6013.00    20438  4.A.2.b.5.I03.D01  03/2014       Analyst
15407     43-6013.00      775  4.A.2.b.5.I03.D01  03/2014       Analyst
15408     43-6013.00      776  4.A.2.a.2.I03.D03  03/2014       Analyst
15409     43-6013.00      776  4.A.3.b.6.I11.D05  03/2014       Analyst
15410     43-6013.00      777  4.A.4.a.3.I03.D11  03/2014       Analyst
15411     43-6013.00      778  4.A.4.a.2.I03.D11  03/2014       Analyst
15412     43-6013.00      779  4.A.4.a.5.I01.D01  03/2014       Analyst
15413     43-6013.00      779  4.A.4.a.5.I10.D02  03/2014       Analyst
15414     43-6013.00      780  4.A.1.a.1.I23.D01  03/2014       Analyst
15415     43-6013.00      781  4.A.3.b.6.I11.D05  03/2014       Analyst
15416     43-6013.00      782  4.A.3.a.3.I01.D01  03/2014       Analyst
15417     43-6013.00      782  4.A.3.b.1.I05.D01  03/2014       Analyst
15418     43-6013.00      783  4.A.4.c.1.I05.D03  03/2014       Analyst
15419     43-6013.00      784  4.A.4.c.3.I05.D01  03/2014       Analyst
15420     43-6013.00      786  4.A.3.b.6.I08.D16  03/2014       Analyst
15421     43-6013.00      786  4.A.3.b.6.I11.D05  03/2014       Analyst
15422     43-6013.00      787  4.A.3.b.6.I10.D03  03/2014       Analyst
15423     43-6013.00      787  4.A.4.c.1.I05.D03  03/2014       Analyst
15424     43-6013.00      787  4.A.4.c.3.I04.D01  03/2014       Analyst
15425     43-6013.00      788  4.A.3.b.6.I13.D05  03/2014       Analyst
15426     43-6013.00      789  4.A.4.c.1.I01.D04  03/2014       Analyst

In [73]:
#Task DWAs ratings:
task_rat = pd.read_table(os.path.join(datasets, 'databases/db2016/Task Ratings.txt'), sep='\t')
task_rat[ task_rat['Task ID'] == 777]    # # Answer telephones and direct calls

,O*NET-SOC Code,Task ID,Scale ID,Category,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Date,Domain Source
117945,43-6013.00,777,FT,1,2.22,110,2.23,0.29,14.87,N,07/2013,Incumbent
117946,43-6013.00,777,FT,2,0.00,110,0.00,n/a,n/a,N,07/2013,Incumbent
117947,43-6013.00,777,FT,3,0.28,110,0.22,0.06,1.32,N,07/2013,Incumbent
117948,43-6013.00,777,FT,4,1.39,110,0.75,0.48,3.99,N,07/2013,Incumbent
117949,43-6013.00,777,FT,5,15.99,110,5.33,7.97,29.47,N,07/2013,Incumbent
117950,43-6013.00,777,FT,6,5.10,110,2.63,1.80,13.61,N,07/2013,Incumbent
117951,43-6013.00,777,FT,7,75.02,110,6.32,60.62,85.42,N,07/2013,Incumbent
117952,43-6013.00,777,IM,n/a,4.69,113,0.07,4.55,4.82,N,07/2013,Incumbent
117953,43-6013.00,777,RT,n/a,95.75,116,2.39,87.54,98.63,N,07/2013,Incumbent

In [16]:
#Categorise Detailed Work Activities, 1-5 increasing frequency. 
task_cats = pd.read_table(os.path.join(datasets, 'databases/db2016/Task Categories.txt'), sep='\t')
task_cats

  Scale ID  Category Category Description
0       FT         1       Yearly or less
1       FT         2     More than yearly
2       FT         3    More than monthly
3       FT         4     More than weekly
4       FT         5                Daily
5       FT         6  Several times daily
6       FT         7       Hourly or more

In [17]:
# tasks_green = pd.read_table(os.path.join(datasets, 'databases/db2016/Tasks to Green DWAs.txt'), sep='\t')
# tasks_green.head()

In [119]:
DWA = pd.read_table(os.path.join(datasets, 'databases/db2016/DWA Reference.txt'), sep='\t')
print "\nnumber of unique Detailed Work Activities = ", DWA["DWA ID"].nunique()
DWA = DWA[ DWA['DWA ID'].isin(taskDWA['DWA ID'].values)]   # restrict the DWA to the 12 SOCs observed 
print "number of unique DWA observed = ", DWA["DWA ID"].nunique()
DWA.head()

print "\nTask 777 falls under DWA: ", DWA[ DWA["DWA ID"] == "4.A.4.a.3.I03.D11"].iloc[0,3]


DWA[ DWA["DWA ID"] == "4.A.4.a.3.I03.D11"]

number of unique Detailed Work Activities =  2070
number of unique DWA observed =  151

Task 777 falls under DWA:  Answer telephones to direct calls or provide information.

,Element ID,IWA ID,DWA ID,DWA Title
1604,4.A.4.a.3,4.A.4.a.3.I03,4.A.4.a.3.I03.D11,Answer telephones to direct calls or provide i...

In [120]:
# Intermediate Work Activity and corresponding WA element ID. 
# Every IWA is linked to exactly one WA from the O*NET Content Model. 
# IWAs are linked to one or more DWAs; 

IWA = pd.read_table(os.path.join(datasets, 'databases/db2016/IWA Reference.txt'), sep='\t')
print "\nnumber of unique Intermediate Work Activities = ", IWA["IWA ID"].nunique()
IWA = IWA[ IWA['IWA ID'].isin(DWA['IWA ID'].values)]   # restrict the IWA to the 12 SOCs observed 
print "number of unique IWA observed = ", IWA["IWA ID"].nunique()
IWA.head()

print "\nTask 777 falls under IWA: ",  IWA[ IWA["IWA ID"] == "4.A.4.a.3.I03"].iloc[0,2]


IWA[ IWA["Element ID"] == "4.A.4.a.3"]

number of unique Intermediate Work Activities =  332
number of unique IWA observed =  93

Task 777 falls under IWA:  Provide information to guests, clients, or customers.

,Element ID,IWA ID,IWA Title
258,4.A.4.a.3,4.A.4.a.3.I02,Provide information or assistance to the public.
259,4.A.4.a.3,4.A.4.a.3.I03,"Provide information to guests, clients, or cus..."

In [128]:
# Work Analysis: Provide a mapping of SOC codes (occupations) to Work Activity ratings.
WA = pd.read_table(os.path.join(datasets, 'databases/db2016/Work Activities.txt'), sep='\t')
print "\nnumber of unique Work Activities = ", WA["Element ID"].nunique()

WA = WA[ WA['O*NET-SOC Code'].isin(df['O*NET-SOC Code'].values)]   # restrict the WA to the 12 SOCs observed 
print "number of unique WA observed = ", WA["Element ID"].nunique()
WA

print "\nMedical Secretary, WA 4.A.4.a.3 (task 777): ", 
WA[ (WA["Element ID"] == "4.A.4.a.3") & (WA["O*NET-SOC Code"] == '43-6013.00')] 
# WA[ WA["O*NET-SOC Code"] == '43-6013.00']    # Medical Secretaries

number of unique Work Activities =  41
number of unique WA observed =  41

Medical Secretary, WA 4.A.4.a.3 (task 777):

,O*NET-SOC Code,Element ID,Element Name,Scale ID,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source
53680,43-6013.00,4.A.4.a.3,Communicating with Persons Outside Organization,IM,3.79,38,0.21,3.36,4.22,N,n/a,07/2013,Incumbent
53681,43-6013.00,4.A.4.a.3,Communicating with Persons Outside Organization,LV,3.63,38,0.40,2.82,4.45,N,N,07/2013,Incumbent

In [129]:
WA['Element_pivot'] =  WA['Element Name'] + " " +  WA['Scale ID']
WA_pivot = WA.pivot(index = 'O*NET-SOC Code', columns='Element_pivot', values='Data Value').fillna(0)
WA_pivot.reset_index(inplace=True)

WA_pivot

Element_pivot,O*NET-SOC Code,Analyzing Data or Information IM,Analyzing Data or Information LV,Assisting and Caring for Others IM,Assisting and Caring for Others LV,Coaching and Developing Others IM,Coaching and Developing Others LV,Communicating with Persons Outside Organization IM,Communicating with Persons Outside Organization LV,"Communicating with Supervisors, Peers, or Subordinates IM",...,Selling or Influencing Others IM,Selling or Influencing Others LV,Staffing Organizational Units IM,Staffing Organizational Units LV,Thinking Creatively IM,Thinking Creatively LV,Training and Teaching Others IM,Training and Teaching Others LV,Updating and Using Relevant Knowledge IM,Updating and Using Relevant Knowledge LV
0,11-9111.00,4.16,5.00,2.92,3.04,4.19,5.35,3.46,4.04,4.58,...,2.27,2.54,3.88,4.92,3.52,4.40,3.88,4.54,4.32,5.68
1,29-1062.00,3.73,4.42,4.44,5.58,2.84,2.99,3.23,3.70,3.95,...,2.51,2.36,1.57,1.50,3.11,3.77,3.21,3.76,4.32,5.32
2,29-1141.00,3.19,3.36,4.85,5.53,3.37,3.99,3.52,3.10,4.44,...,1.70,1.27,2.12,1.64,3.22,3.69,3.94,3.91,4.55,5.44
3,29-1171.00,4.03,4.87,4.90,6.40,3.77,4.87,3.70,4.30,4.47,...,2.87,3.00,2.37,3.14,3.33,4.10,3.93,4.69,4.73,6.00
4,29-2052.00,3.29,3.36,3.89,4.48,2.81,2.96,3.34,3.06,3.94,...,2.63,2.37,2.20,1.92,2.88,2.95,3.08,3.10,3.74,4.59
5,29-2071.00,3.44,3.73,2.71,2.29,2.25,2.02,3.29,3.35,4.18,...,1.29,0.41,1.45,0.80,2.85,3.03,2.53,1.90,4.11,5.02
6,31-1014.00,2.77,2.95,4.76,4.43,3.29,2.92,2.99,2.16,4.41,...,2.25,1.13,2.09,0.98,2.80,2.50,3.66,2.93,3.12,3.34
7,31-9092.00,3.57,3.66,4.73,5.31,3.02,3.53,3.62,3.82,4.37,...,2.53,2.38,2.08,1.77,3.05,3.60,3.53,3.55,4.10,5.08
8,31-9097.00,3.20,3.00,4.50,5.20,3.57,3.76,3.70,3.40,4.10,...,1.85,1.50,2.52,2.05,2.70,2.80,3.90,4.00,4.20,5.00
9,43-4171.00,2.38,2.16,3.83,3.91,2.69,2.80,3.93,3.62,4.20,...,2.11,1.77,1.51,0.53,2.77,2.67,2.90,2.54,3.81,4.32
10,43-6013.00,3.15,3.30,3.61,3.71,2.43,2.40,3.79,3.63,3.89,...,1.83,1.33,2.00,1.39,2.49,2.05,2.49,1.83,3.80,3.98

In [22]:
# "Medical Records and Health Information Technicians Bright Outlook" Tasks:

# tasks = pd.read_table(os.path.join(datasets, 'databases/db2016/Task Statements.txt'), sep='\t')
# tasks[ tasks['O*NET-SOC Code'] == '29-2071.00']

In [23]:
#Education: 
edu = pd.read_table(os.path.join(datasets, 'databases/db2016/Education, Training, and Experience.txt'), sep='\t')
edu = edu[edu['Data Value'] != 0.0]
# edu.head()

# edu[ edu['O*NET-SOC Code'] == '29-2071.00']

In [24]:
#Technoogy:
tech = pd.read_table(os.path.join(datasets, 'databases/db2016/Tools and Technology.txt'), sep='\t')
# tech[tech['Hot Technology'] == 'Y'].head()
# tech.head()

# tech[ tech['O*NET-SOC Code'] == '43-6013.00']  # # Medical Records and Health Information Technicians

In [131]:
#SKills:
skills = pd.read_table(os.path.join(datasets, 'databases/db2016/Skills.txt'), sep='\t')
print "\nnumber of unique Skills = ", skills["Element ID"].nunique()
skills = skills[ skills['O*NET-SOC Code'].isin(df['O*NET-SOC Code'].values)]

#  skills[ skills['O*NET-SOC Code'] == '43-6013.00']

skills['Element_pivot'] =  skills['Element Name'] + " " +  skills['Scale ID']
skills

number of unique Skills =  35

,O*NET-SOC Code,Element ID,Element Name,Scale ID,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source,Element_pivot
2730,11-9111.00,2.A.1.a,Reading Comprehension,IM,4.00,8,0.00,4.00,4.00,N,n/a,07/2016,Analyst,Reading Comprehension IM
2731,11-9111.00,2.A.1.a,Reading Comprehension,LV,4.12,8,0.13,3.88,4.37,N,N,07/2016,Analyst,Reading Comprehension LV
2732,11-9111.00,2.A.1.b,Active Listening,IM,4.00,8,0.00,4.00,4.00,N,n/a,07/2016,Analyst,Active Listening IM
2733,11-9111.00,2.A.1.b,Active Listening,LV,4.00,8,0.00,4.00,4.00,N,N,07/2016,Analyst,Active Listening LV
2734,11-9111.00,2.A.1.c,Writing,IM,4.00,8,0.00,4.00,4.00,N,n/a,07/2016,Analyst,Writing IM
2735,11-9111.00,2.A.1.c,Writing,LV,4.00,8,0.00,4.00,4.00,N,N,07/2016,Analyst,Writing LV
2736,11-9111.00,2.A.1.d,Speaking,IM,4.25,8,0.16,3.93,4.57,N,n/a,07/2016,Analyst,Speaking IM
2737,11-9111.00,2.A.1.d,Speaking,LV,4.00,8,0.00,4.00,4.00,N,N,07/2016,Analyst,Speaking LV
2738,11-9111.00,2.A.1.e,Mathematics,IM,2.75,8,0.16,2.43,3.07,N,n/a,07/2016,Analyst,Mathematics IM
2739,11-9111.00,2.A.1.e,Mathematics,LV,2.88,8,0.13,2.63,3.12,N,N,07/2016,Analyst,Mathematics LV
2740,11-9111.00,2.A.1.f,Science,IM,2.75,8,0.16,2.43,3.07,N,n/a,07/2016,Analyst,Science IM
2741,11-9111.00,2.A.1.f,Science,LV,3.12,8,0.30,2.55,3.70,N,N,07/2016,Analyst,Science LV
2742,11-9111.00,2.A.2.a,Critical Thinking,IM,4.12,8,0.13,3.88,4.37,N,n/a,07/2016,Analyst,Critical Thinking IM
2743,11-9111.00,2.A.2.a,Critical Thinking,LV,4.00,8,0.00,4.00,4.00,N,N,07/2016,Analyst,Critical Thinking LV
2744,11-9111.00,2.A.2.b,Active Learning,IM,3.88,8,0.13,3.63,4.12,N,n/a,07/2016,Analyst,Active Learning IM
2745,11-9111.00,2.A.2.b,Active Learning,LV,4.00,8,0.00,4.00,4.00,N,N,07/2016,Analyst,Active Learning LV
2746,11-9111.00,2.A.2.c,Learning Strategies,IM,3.12,8,0.13,2.88,3.37,N,n/a,07/2016,Analyst,Learning Strategies IM
2747,11-9111.00,2.A.2.c,Learning Strategies,LV,3.75,8,0.16,3.43,4.07,N,N,07/2016,Analyst,Learning Strategies LV
2748,11-9111.00,2.A.2.d,Monitoring,IM,3.62,8,0.18,3.27,3.98,N,n/a,07/2016,Analyst,Monitoring IM
2749,11-9111.00,2.A.2.d,Monitoring,LV,4.00,8,0.00,4.00,4.00,N,N,07/2016,Analyst,Monitoring LV
2750,11-9111.00,2.B.1.a,Social Perceptiveness,IM,3.88,8,0.13,3.63,4.12,N,n/a,07/2016,Analyst,Social Perceptiveness IM
2751,11-9111.00,2.B.1.a,Social Perceptiveness,LV,4.00,8,0.00,4.00,4.00,N,N,07/2016,Analyst,Social Perceptiveness LV
2752,11-9111.00,2.B.1.b,Coordination,IM,4.00,8,0.00,4.00,4.00,N,n/a,07/2016,Analyst,Coordination IM
2753,11-9111.00,2.B.1.b,Coordination,LV,4.25,8,0.16,3.93,4.57,N,N,07/2016,Analyst,Coordination LV
2754,11-9111.00,2.B.1.c,Persuasion,IM,3.62,8,0.18,3.27,3.98,N,n/a,07/2016,Analyst,Persuasion IM
2755,11-9111.00,2.B.1.c,Persuasion,LV,3.50,8,0.19,3.13,3.87,N,N,07/2016,Analyst,Persuasion LV
2756,11-9111.00,2.B.1.d,Negotiation,IM,3.50,8,0.19,3.13,3.87,N,n/a,07/2016,Analyst,Negotiation IM
2757,11-9111.00,2.B.1.d,Negotiation,LV,3.38,8,0.18,3.02,3.73,N,N,07/2016,Analyst,Negotiation LV
2758,11-9111.00,2.B.1.e,Instructing,IM,3.62,8,0.18,3.27,3.98,N,n/a,07/2016,Analyst,Instructing IM
2759,11-9111.00,2.B.1.e,Instructing,LV,3.50,8,0.19,3.13,3.87,N,N,07/2016,Analyst,Instructing LV
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45820,43-6013.00,2.B.3.d,Installation,IM,1.00,8,0.00,1.00,1.00,N,n/a,07/2013,Analyst,Installation IM
45821,43-6013.00,2.B.3.d,Installation,LV,0.00,8,0.00,0.00,0.00,N,Y,07/2013,Analyst,Installation LV
45822,43-6013.00,2.B.3.e,Programming,IM,1.25,8,0.16,1.00,1.57,N,n/a,07/2013,Analyst,Programming IM
45823,43-6013.00,2.B.3.e,Programming,LV,0.25,8,0.16,0.00,0.57,N,Y,07/2013,Analyst,Programming LV
45824,43-6013.00,2.B.3.g,Operation Monitoring,IM,1.88,8,0.13,1.63,2.12,N,n/a,07/2013,Analyst,Operation Monitoring IM
45825,43-6013.00,2.B.3.g,Operation Monitoring,LV,1.12,8,0.23,0.68,1.57,N,N,07/2013,Analyst,Operation Monitoring LV
45826,43-6013.00,2.B.3.h,Operation and Control,IM,1.00,8,0.00,1.00,1.00,N,n/a,07/2013,Analyst,Operation and Control IM
45827,43-6013.00,2.B.3.h,Operation and Control,LV,0.00,8,0.00,0.00,0.00,N,Y,07/2013,Analyst,Operation and Control LV
45828,43-6013.00,2.B.3.j,Equipment Maintenance,IM,1.00,8,0.00,1.00,1.00,N,n/a,07/2013,Analyst,Equipment Maintenance IM
45829,43-6013.00,2.B.3.j,Equipment Maintenance,LV,0.00,8,0.00,0.00,0.00,N,Y,07/2013,Analyst,Equipment Maintenance LV
45830,43-6013.00,2.B.3.k,Troubleshooting,IM,1.00,8,0.00,1.00,1.00,N,n/a,07/2013,Analyst,Troubleshooting IM
45831,43-6013.00,2.B.3.k,Troubleshooting,LV,0.00,8,0.00,0.00,0.00,N,Y,07/2013,Analyst,Troubleshooting LV
45832,43-6013.00,2.B.3.l,Repairing,IM,1.00,8,0.00,1.00,1.00,N,n/a,07/2013,Analyst,Repairing IM
45833,43-6013.00,2.B.3.l,Repairing,LV,0.00,8,0.00,0.00,0.00,N,Y,07/2013,Analyst,Repairing LV
45834,43-6013.00,2.B.3.m,Quality Control Analysis,IM,1.12,8,0.13,1.00,1.37,N,n/a,07/2013,Analyst,Quality Control Analysis IM
45835,43-6013.00,2.B.3.m,Quality Control Analysis,LV,0.25,8,0.25,0.00,0.74,N,Y,07/2013,Analyst,Quality Control Analysis LV
45836,43-6013.00,2.B.4.e,Judgment and Decision Making,IM,2.75,8,0.16,2.43,3.07,N,n/a,07/2013,Analyst,Judgment and Decision Making IM
45837,43-6013.00,2.B.4.e,Judgment and Decision Making,LV,2.38,8,0.18,2.02,2.73,N,N,07/2013,Analyst,Judgment and Decision Making LV
45838,43-6013.00,2.B.4.g,Systems Analysis,IM,2.00,8,0.00,2.00,2.00,N,n/a,07/2013,Analyst,Systems Analysis IM
45839,43-6013.00,2.B.4.g,Systems Analysis,LV,2.12,8,0.13,1.88,2.37,N,N,07/2013,Analyst,Systems Analysis LV
45840,43-6013.00,2.B.4.h,Systems Evaluation,IM,2.00,8,0.00,2.00,2.00,N,n/a,07/2013,Analyst,Systems Evaluation IM
45841,43-6013.00,2.B.4.h,Systems Evaluation,LV,1.88,8,0.13,1.63,2.12,N,N,07/2013,Analyst,Systems Evaluation LV
45842,43-6013.00,2.B.5.a,Time Management,IM,3.12,8,0.13,2.88,3.37,N,n/a,07/2013,Analyst,Time Management IM
45843,43-6013.00,2.B.5.a,Time Management,LV,2.88,8,0.13,2.63,3.12,N,N,07/2013,Analyst,Time Management LV
45844,43-6013.00,2.B.5.b,Management of Financial Resources,IM,1.38,8,0.26,1.00,1.89,N,n/a,07/2013,Analyst,Management of Financial Resources IM
45845,43-6013.00,2.B.5.b,Management of Financial Resources,LV,0.38,8,0.26,0.00,0.89,N,Y,07/2013,Analyst,Management of Financial Resources LV
45846,43-6013.00,2.B.5.c,Management of Material Resources,IM,1.38,8,0.26,1.00,1.89,N,n/a,07/2013,Analyst,Management of Material Resources IM
45847,43-6013.00,2.B.5.c,Management of Material Resources,LV,0.62,8,0.42,0.00,1.45,N,Y,07/2013,Analyst,Management of Material Resources LV
45848,43-6013.00,2.B.5.d,Management of Personnel Resources,IM,2.75,8,0.16,2.43,3.07,N,n/a,07/2013,Analyst,Management of Personnel Resources IM
45849,43-6013.00,2.B.5.d,Management of Personnel Resources,LV,2.12,8,0.23,1.68,2.57,N,N,07/2013,Analyst,Management of Personnel Resources LV

In [74]:
# WA[ (WA["Element ID"] == "2.A.1.a")

# print skills['Element Name'].unique()
# print len(skills['Element Name'].unique())
# skills[ skills['O*NET-SOC Code'] == '43-4199.00']    # Not in Skills dataset

Empty DataFrame
Columns: [O*NET-SOC Code, Element ID, Element Name, Scale ID, Data Value, N, Standard Error, Lower CI Bound, Upper CI Bound, Recommend Suppress, Not Relevant, Date, Domain Source, Element_pivot]
Index: []

In [133]:
skills_pivot = skills.pivot(index = 'O*NET-SOC Code', columns='Element_pivot', values='Data Value').fillna(0)
skills_pivot.reset_index(inplace=True)
skills_pivot

Element_pivot,O*NET-SOC Code,Active Learning IM,Active Learning LV,Active Listening IM,Active Listening LV,Complex Problem Solving IM,Complex Problem Solving LV,Coordination IM,Coordination LV,Critical Thinking IM,...,Systems Evaluation IM,Systems Evaluation LV,Technology Design IM,Technology Design LV,Time Management IM,Time Management LV,Troubleshooting IM,Troubleshooting LV,Writing IM,Writing LV
0,11-9111.00,3.88,4.00,4.00,4.00,3.75,3.38,4.00,4.25,4.12,...,3.75,3.50,2.00,1.12,4.00,4.00,1.25,0.25,4.00,4.00
1,29-1062.00,3.75,4.00,4.25,4.75,4.00,4.12,3.25,4.00,4.38,...,2.88,3.38,1.25,0.38,3.62,3.88,1.50,0.62,4.12,4.25
2,29-1141.00,3.38,3.75,4.12,4.00,3.38,3.25,3.88,4.12,3.88,...,2.88,3.25,1.75,0.88,3.00,3.38,1.75,1.50,3.62,3.62
3,29-1171.00,4.12,4.12,4.12,4.50,4.00,4.00,3.75,3.62,4.12,...,3.25,3.25,1.75,0.88,3.38,3.75,1.75,1.38,3.75,4.00
4,29-2052.00,2.88,3.00,3.88,3.88,3.00,2.62,3.00,3.00,3.25,...,2.12,1.88,1.62,0.62,3.12,2.75,1.75,0.88,2.88,2.88
5,29-2071.00,2.50,2.50,3.00,3.12,2.75,2.62,2.38,2.12,3.00,...,1.88,1.75,1.75,0.75,2.88,2.75,1.12,0.12,3.00,3.00
6,31-1014.00,2.50,2.50,3.62,3.00,2.75,2.38,3.25,2.88,3.12,...,2.00,1.50,1.50,0.75,2.88,2.25,1.88,1.25,2.88,2.75
7,31-9092.00,3.25,3.38,3.88,3.88,2.75,3.00,3.50,3.38,3.62,...,2.50,2.75,1.38,0.38,3.25,2.88,1.75,1.50,3.50,3.25
8,31-9097.00,2.88,3.00,3.50,3.38,2.62,2.38,3.00,3.12,3.25,...,2.12,1.62,1.50,0.75,2.88,2.75,2.00,1.50,3.12,3.00
9,43-4171.00,3.00,2.38,3.62,3.38,2.50,2.75,3.12,2.75,3.25,...,2.25,2.00,1.38,0.50,2.88,2.75,1.38,0.38,3.25,3.12
10,43-6013.00,2.12,2.38,3.88,3.75,3.00,2.62,3.12,2.88,3.00,...,2.00,1.88,1.00,0.00,3.12,2.88,1.00,0.00,3.12,3.12

In [134]:
# result = pd.concat([df, skills_pivot], axis=1, join_axes=[df['O*NET-SOC Code']]) 

result1 = pd.merge(df, skills_pivot,  how='left', left_on=['O*NET-SOC Code'], right_on = ['O*NET-SOC Code'])
result1 # [result['O*NET-SOC Code'] == '29-1062.00']

result = pd.merge(result1, WA_pivot,  how='left', left_on=['O*NET-SOC Code'], right_on = ['O*NET-SOC Code'])

result

,Observed Occupation,O*NET-SOC Code,O*NET Occupation title,Description,Active Learning IM,Active Learning LV,Active Listening IM,Active Listening LV,Complex Problem Solving IM,Complex Problem Solving LV,...,Selling or Influencing Others IM,Selling or Influencing Others LV,Staffing Organizational Units IM,Staffing Organizational Units LV,Thinking Creatively IM,Thinking Creatively LV,Training and Teaching Others IM,Training and Teaching Others LV,Updating and Using Relevant Knowledge IM,Updating and Using Relevant Knowledge LV
0,General Practitioner,29-1062.00,Family and General Practitioners,"Physicians who diagnose, treat, and help preve...",3.75,4.00,4.25,4.75,4.00,4.12,...,2.51,2.36,1.57,1.50,3.11,3.77,3.21,3.76,4.32,5.32
1,Scanning Clerk,43-4199.00,"Information and Record Clerks, All Other",All information and record clerks not listed s...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Healthcare Assistant,31-9092.00,Medical Assistants,Perform administrative and certain clinical du...,3.25,3.38,3.88,3.88,2.75,3.00,...,2.53,2.38,2.08,1.77,3.05,3.60,3.53,3.55,4.10,5.08
3,Administrator,29-2071.00,Medical Records and Health Information Technic...,"Compile, process, and maintain medical records...",2.50,2.50,3.00,3.12,2.75,2.62,...,1.29,0.41,1.45,0.80,2.85,3.03,2.53,1.90,4.11,5.02
4,Secretary,43-6013.00,Medical Secretaries,Perform secretarial duties using specific know...,2.12,2.38,3.88,3.75,3.00,2.62,...,1.83,1.33,2.00,1.39,2.49,2.05,2.49,1.83,3.80,3.98
5,Practice manager,11-9111.00,Medical and Health Services Managers,"Plan, direct, or coordinate medical and health...",3.88,4.00,4.00,4.00,3.75,3.38,...,2.27,2.54,3.88,4.92,3.52,4.40,3.88,4.54,4.32,5.68
6,Practice nurse,29-1171.00,Nurse Practitioners,"Diagnose and treat acute, episodic, or chronic...",4.12,4.12,4.12,4.50,4.00,4.00,...,2.87,3.00,2.37,3.14,3.33,4.10,3.93,4.69,4.73,6.00
7,Healthcare Assistant,31-1014.00,Nursing Assistants,Provide basic patient care under direction of ...,2.50,2.50,3.62,3.00,2.75,2.38,...,2.25,1.13,2.09,0.98,2.80,2.50,3.66,2.93,3.12,3.34
8,Pharmacy technician,29-2052.00,Pharmacy Technicians,Prepare medications under the direction of a p...,2.88,3.00,3.88,3.88,3.00,2.62,...,2.63,2.37,2.20,1.92,2.88,2.95,3.08,3.10,3.74,4.59
9,Phlebotomists,31-9097.00,Phlebotomists,"Draw blood for tests, transfusions, donations,...",2.88,3.00,3.50,3.38,2.62,2.38,...,1.85,1.50,2.52,2.05,2.70,2.80,3.90,4.00,4.20,5.00
10,Receptionist,43-4171.00,Receptionists and Information Clerks,Answer inquiries and provide information to th...,3.00,2.38,3.62,3.38,2.50,2.75,...,2.11,1.77,1.51,0.53,2.77,2.67,2.90,2.54,3.81,4.32
11,Practice nurse,29-1141.00,Registered Nurses,"Assess patient health problems and needs, deve...",3.38,3.75,4.12,4.00,3.38,3.25,...,1.70,1.27,2.12,1.64,3.22,3.69,3.94,3.91,4.55,5.44

In [135]:
output_doc = os.path.join(datasets, 'FoHC/Observed_occ_onet_data.csv')
result.to_csv(output_doc)